---
title: "Prueba"
author: "Beatriz Jiménez Franco"
date: "6/12/2020"
output: ioslides_presentation
runtime: shiny
---

NO SALE, ALGO HAGO MAL

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Shiny Presentation

This R Markdown presentation is made interactive using Shiny. The viewers of the presentation can change the assumptions underlying what's presented and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

## Interactive Plot

```{r eruptions, message=FALSE, warning=FALSE}
library(shiny)
library(plotly)
library(datasets)
data("faithful")
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)

library(datasets)
data(faithful)
renderPlotly({
  plot_ly(data = faithful,x = ~eruptions, type = "histogram",  breaks = as.numeric(input$n_breaks),  adjust = input$bw_adjust)
})
```




